__author__ = 'cwallace'

from optparse import OptionParser
import os
from shutil import copyfile


def make_folders_for_sorting(dest):
    list = ["default", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

    for name in list:
        new_dir = os.path.join(dest, name)
        try:
            os.stat(new_dir + "_good")
        except:
            os.mkdir(new_dir + "_good")
        try:
            os.stat(new_dir + "_bad")
        except:
            os.mkdir(new_dir + "_bad")


def main():
    parser = OptionParser()
    parser.add_option("-p", "--pkitsFolder", dest="pkits_folder", default="",
                      help="Folder containing certs from a PKITS edition")
    parser.add_option("-r", "--rootFolder", dest="root_folder", default="",
                      help="Folder to receive folders organized to facilitate batch processing (i.e., default_good, default_bad, 1_good, 1_bad, etc.)")
    parser.add_option("-c", "--csvFile", dest="csv_file", default="",
                      help="CSV file generated by PkitsTableGenerator utility")

    (options, args) = parser.parse_args()

    make_folders_for_sorting(options.root_folder)

    for line in open(options.csv_file):
        csv_row = line.rstrip().split(",")

        file = csv_row[1]
        settings = csv_row[2].lower().replace("settings", "")
        if "0" == csv_row[3]:
            dest_folder = settings + "_good"
        else:
            dest_folder = settings + "_bad"

        try:
            src = os.path.join(options.pkits_folder, file)
            dest = os.path.join(options.root_folder, dest_folder, file)
            copyfile(src, dest)
        except Exception as e:
            print(str(e))


if __name__ == '__main__':
    main()